<?php

namespace Database\Seeders;

use App\Enums\VehicleOwnerType;
use App\Enums\VehicleStatus;
use App\Enums\VehicleType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RentedVehicleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('vehicles')->where('type', VehicleOwnerType::Rent->value)->delete();

        $now = now();

        $vehicles = [
            ['plate_number' => '29H32499', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76664', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K02462', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37531', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24382', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86372', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37752', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70673', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C35241', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H48111', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71656', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98733', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96871', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H23260', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K15629', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32121', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32502', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H90062', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H13106', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70624', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05818', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86959', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H78496', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71542', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E13130', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K13106', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E35232', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E35431', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75625', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H78392', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H80037', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H85429', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '88H04914', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86886', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H89075', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H38112', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72990', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H98554', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '51D30321', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25717', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H80463', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56531', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05514', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E29739', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05760', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56582', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99607', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99663', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86823', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56513', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29B10527', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E51849', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29LD50274', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98096', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56550', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '88H05108', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E81502', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H98328', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05408', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C82502', 'owner' => 'ACE', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '15H02376', 'owner' => 'ASGS', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '15H06810', 'owner' => 'ASGS', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '15H17946', 'owner' => 'ASGS', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '15H08970', 'owner' => 'ASGS', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '15H09876', 'owner' => 'ASGS', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72838', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05636', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44229', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56694', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E15382', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56480', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K11640', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19150', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E45567', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K10272', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E13383', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E49172', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26113', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05969', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E58692', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E66211', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37537', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99665', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25932', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26737', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E51591', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E61678', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24855', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75636', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95104', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95223', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99599', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '20H06527', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E08318', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E11496', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19162', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E68852', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26341', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75914', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99579', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E21440', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79097', 'owner' => 'CBT', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99H01315', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H04190', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29H95476', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29H40752', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29C19534', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29H93725', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20C06556', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20H01496', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29H75703', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20H00255', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20C19534', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20C75703', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H00222', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20H01677', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H00871', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29C40752', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29C42434', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H02019', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98C20267', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '34C19239', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '29H12799', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '99C18188', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C54285', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H83775', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C34519', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '98H01511', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '98H03662', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C56206', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H83755', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '99H02074', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '98H00674', 'owner' => 'CMC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '20C07081', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98E01072', 'owner' => 'CMC', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '30X3598', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30U1804', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C23025', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C93949', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C63852', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C94013', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C63050', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C63052', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C47286', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C25892', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C25813', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C92267', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C49009', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C17958', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C02786', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C44016', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C19427', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C92848', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C02903', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C17075', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C08396', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C17942', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30T4587', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C63112', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95547', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95368', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C33194', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30Z5556', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C15770', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C92096', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95407', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C31493', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C92911', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30V7733', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C44068', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C49213', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C26900', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C40520', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95508', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C47002', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C11115', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C63053', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C02904', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30Y8347', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H71580', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76865', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37835', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C69225', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C16311', 'owner' => 'Dương Anh', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H05776', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C33365', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H32462', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95152', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C23199', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C42197', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '51C37909', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '20H0577', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '65C00834', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H27417', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C22997', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C95940', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C52622', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96496', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C55225', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44462', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C42393', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73154', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C95104', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72707', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24659', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79156', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79141', 'owner' => 'Gia Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C80245', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H30908', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H86602', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H05117', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E07354', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H75661', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70655', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '89C20357', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '30L77308', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29G02174', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E36456', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E36397', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E36128', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E40364', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E41913', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H85596', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E22087', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E68863', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H65760', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '89H04773', 'owner' => 'Hải Như', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C51184', 'owner' => 'HMA', 'vehicle_type' => VehicleType::BatWing->value],
            ['plate_number' => '29C91489', 'owner' => 'HMA', 'vehicle_type' => VehicleType::BatWing->value],
            ['plate_number' => '29E26221', 'owner' => 'HMA', 'vehicle_type' => VehicleType::BatWing->value],
            ['plate_number' => '29H70616', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H99630', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H99453', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H70583', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H75838', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H70853', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H99339', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29E15360', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29E38020', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29K05944', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29E61763', 'owner' => 'HMA', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C83126', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C38080', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C25810', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H16088', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C91099', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C99043', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C20997', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C95788', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C96117', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C98493', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C99817', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H19099', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H24640', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H20904', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H37166', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H37744', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H15133', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70710', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70711', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '9H70710', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H81299', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H99043', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C99590', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H81454', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H24630', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H71772', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70770', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H16008', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05775', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C96177', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E26218', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E14703', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E25766', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E72475', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E73145', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H95131', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90092', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96394', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C93472', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H03497', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C10528', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96852', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C25804', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27785', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C91221', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90880', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C62833', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C23759', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C64668', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C50921', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C99267', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C49115', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C41743', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C95792', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C99345', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20491', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C62832', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24342', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C46486', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96364', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C99077', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H16749', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C41971', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C93761', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C31402', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C41851', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C93302', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C33056', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C91101', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C25533', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32944', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C25549', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27018', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C51261', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C41831', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C93759', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90701', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H16908', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C52939', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C41965', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C92939', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32082', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27772', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24209', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C92225', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C32763', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37995', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24274', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40137', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C11604', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70651', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C38272', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H45371', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70787', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90783', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90940', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37462', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27552', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44170', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C92119', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71543', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40352', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73029', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C46890', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76905', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76913', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76911', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98832', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76732', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C47071', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75707', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81186', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81408', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71509', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72832', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H82411', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C31259', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C91076', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C94432', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C42217', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C48813', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84182', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H80176', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84141', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44172', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84183', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H83585', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88359', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81285', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C47196', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C91897', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37692', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44156', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76892', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88372', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C99866', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76538', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92048', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C92629', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24678', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '88H02532', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71523', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H82447', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81356', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32096', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86368', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99C20574', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27030', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99790', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99749', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71646', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H65121', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95261', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95069', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76897', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24560', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72981', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95052', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75859', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88352', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40521', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99662', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '17C12351', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92079', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05945', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05442', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99568', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05620', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E03447', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79191', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75563', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05484', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20092', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75704', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C27252', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76996', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81455', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05702', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79129', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95103', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29F05924', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92153', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05833', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K10413', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C99694', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84132', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C52571', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98662', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20360', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24381', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71659', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79327', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99390', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26731', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E21604', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05519', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E14741', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25823', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40766', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E14720', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E14746', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26201', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27187', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70720', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75693', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76957', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88332', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92016', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99640', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05422', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05722', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75771', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C90319', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25793', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05805', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26241', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27007', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05984', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25960', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25783', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C63440', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37251', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26706', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84167', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92019', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38459', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29F05632', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05515', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H95058', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27476', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84256', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H57927', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05565', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40589', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99526', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19108', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25784', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C55694', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05624', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C94229', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26090', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38455', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20016', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92157', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99696', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40053', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C20092', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05580', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99332', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25997', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99538', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '34C27943', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H86374', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E14718', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E73174', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76525', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26694', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25904', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E61683', 'owner' => 'HMA', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99C19489', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H00899', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H01123', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '15C08131', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H01091', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '34G00457', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '20C23195', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '34C23813', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98E01128', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H03639', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H03640', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H04164', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02060', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02261', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02405', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99E01615', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H00205', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02061', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99F00970', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99E00721', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99A75479', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H00267', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H03383', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02629', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98G00348', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98C22723', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H02642', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '99H04809', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '98H01615', 'owner' => 'Hoàng Gia', 'vehicle_type' => VehicleType::Container->value],
            ['plate_number' => '37H10582', 'owner' => 'MFD', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '37H10567', 'owner' => 'MFD', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '37H08422', 'owner' => 'MFD', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '37H17746', 'owner' => 'MFD', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E54946', 'owner' => 'NQH', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E39205', 'owner' => 'NQH', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E39163', 'owner' => 'NQH', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98544', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24520', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H24643', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H76792', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C37835', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C65638', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '99C12432', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C93854', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C92160', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C42535', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C42325', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C57996', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C94138', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C58169', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C57835', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H16167', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H24486', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C94495', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C98172', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C99471', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C77022', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C98944', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H27932', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H16885', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70641', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H40598', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H32315', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C38784', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H24460', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70744', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70663', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H75414', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H75855', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C66929', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '79C09719', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H76517', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H76819', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H16884', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H83575', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H57424', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H70614', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29F05985', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H88337', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H88397', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H95015', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H37799', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05976', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05633', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H76514', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '99H02527', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H79107', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H20261', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H92126', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05626', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05590', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29C99732', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E26078', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H81296', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E26076', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05596', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H02738', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E60484', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E61785', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E72490', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29K05698', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H24690', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H22334', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70760', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20283', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71723', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H45344', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70191', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99C12112', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27039', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20396', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75944', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73165', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73059', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H22548', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '98H00308', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76713', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75921', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H22788', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76887', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79237', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79416', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40919', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72829', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C51096', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81482', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40829', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70670', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H80860', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88389', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H83578', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70818', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72843', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73022', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73158', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27727', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99563', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92180', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05655', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H83591', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75749', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05672', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70692', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '98H00786', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92117', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05432', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E33903', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72157', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H94922', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C25501', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C84294', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26087', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81121', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81313', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H82121', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75980', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92049', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88371', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70769', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81494', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38010', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37726', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C98846', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25841', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19117', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19523', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E25824', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H92096', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19370', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19591', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05562', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32829', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19056', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38051', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40756', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75558', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C64515', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C91136', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73034', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H75998', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99765', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76783', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76986', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '98H07246', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H80353', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26061', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20200', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38055', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26051', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05676', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E26577', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27651', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C12412', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E61707', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E65901', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05816', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88313', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99618', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19585', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E65972', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40614', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73008', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99734', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29K05909', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H88330', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99H06967', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H16607', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H81154', 'owner' => 'Tam Bảo', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E66122', 'owner' => 'Thánh Gióng', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E45582', 'owner' => 'Thánh Gióng', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E19198', 'owner' => 'Thánh Gióng', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E56449', 'owner' => 'Thánh Gióng', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E66134', 'owner' => 'Thánh Gióng', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H84476', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H84482', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C04643', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C34551', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H19198', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29K04961', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H09329', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H12806', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29C56121', 'owner' => 'VFC', 'vehicle_type' => VehicleType::AntiVibration->value],
            ['plate_number' => '29H24037', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C94092', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70661', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71586', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20344', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72822', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32005', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H32988', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H76850', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27745', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C96512', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H79346', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70722', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70793', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71652', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71690', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71565', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H82493', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H10049', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72872', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24075', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72948', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71553', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70802', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24625', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72856', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73164', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24071', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C57638', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71593', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71731', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72936', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27832', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H99564', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C92264', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H20123', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24973', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H71733', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73115', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C11388', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H72953', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40344', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24919', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H27528', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C24037', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37336', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H40568', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H70741', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24731', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H73183', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E38017', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H37378', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H55801', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H24060', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C55801', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29C44037', 'owner' => 'VT 123', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29H09122', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99H04569', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '99H08674', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E33135', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '29E36355', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Normal->value],
            ['plate_number' => '12C06424', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29H05649', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Cold->value],
            ['plate_number' => '29E80464', 'owner' => 'CLC', 'vehicle_type' => VehicleType::Cold->value],
        ];

        $chunks = array_chunk($vehicles, 100);
        foreach ($chunks as $chunk) {
            $data = array_map(function ($v) use ($now) {
                return [
                    'plate_number' => $v['plate_number'],
                    'owner' => $v['owner'],
                    'load_capacity' => $v['load_capacity'] ?? null,
                    'type' => VehicleOwnerType::Rent->value,
                    'vehicle_type' => $v['vehicle_type'] ?? VehicleType::Normal->value,
                    'status' => VehicleStatus::On->value,
                    'current_mileage' => 10000,
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }, $chunk);

            DB::table('vehicles')->upsert(
                $data,
                ['plate_number'],
                ['owner', 'load_capacity', 'type', 'vehicle_type', 'status', 'is_active', 'updated_at']
            );
        }
    }
}
